### PR TITLE
Logitech F310 complete config

### PR DESCRIPTION
**Pull request by acklenx**
Completed the non-generic Logitech config file to include all buttons.  Gave a matching description and created and example that shows the output of all buttons and axes.

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi, @acklenx this is great! Can you please run `make lint` and "fix" anything that the linter complains about, than add to this PR? Thank you very much!

**Comment by acklenx** [comment]
I'm not sure how... I grabbed eslint and tried to run that since I thought that's what the whole cylon project switched to.  After a couple of attempts I think I've reached a point where it's not only my fault ;)  But I can't get past this point...

-----------------------------------------------------------------------------------------------

C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\config-validator.js:88
        throw new Error(message.join(""));
              ^
Error: C:\Dev\johnny-five\node_modules\cylon-joystick\.eslintrc:
        Configuration for rule "comma-dangle" is invalid:
        Value "always-multiline" is the wrong type.

    at validateRuleOptions (C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\config-validator.js:88:15)
    at C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\config-validator.js:101:13
    at Array.forEach (native)
    at Object.validate (C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\config-validator.js:100:35)
    at loadConfig (C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\config.js:99:19)
    at getLocalConfig (C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\config.js:225:23)
    at Config.getConfig (C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\config.js:363:22)
    at processText (C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:183:27)
    at processFile (C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:226:12)
    at C:\Users\AcklenX\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:322:26

**Comment by deadprogram** [comment]
Now that I sent you on this path, I have to at least help get out of it. :mountain_bicyclist: 

Please give me a little while, and I'll look to see what's up. Thanks!

**Comment by edgarsilva** [comment]
This file contains the fixes for your PR, you are just missint spaces, but it seems your .eslintrc has some issues as well. Just delete that .eslintrc file and use the one inside cylon-joystick at the module level.

```javascript
"use strict";

var Cylon = require("cylon");

Cylon.robot({
  connections: {
    joystick: { adaptor: "joystick" }
  },

  devices: {
    controller: { driver: "joystick", config: "./config/logitech-f310" }
  },

  work: function(my) {
    var buttons = ["up", "down", "left", "right", "start", "select",
                   "home", "ls", "rs", "lb", "rb", "a", "b", "y", "x"];

    buttons.forEach(function(button) {
      my.controller.on(button + ":press", function() {
        console.log("Button " + button + " pressed.");
      });

      my.controller.on(button + ":release", function() {
        console.log("Button " + button + " released.");
      });
    });

    my.controller.on("left_x:move", function(pos) {
      console.log("Left Stick - X:", pos);
    });

    my.controller.on("left_z:move", function(pos) {
      console.log("Left Shoulder - Z:", pos);
    });

    my.controller.on("right_x:move", function(pos) {
      console.log("Right Stick - X:", pos);
    });

    my.controller.on("left_y:move", function(pos) {
      console.log("Left Stick - Y:", pos);
    });

    my.controller.on("right_y:move", function(pos) {
      console.log("Right Stick - Y:", pos);
    });

    my.controller.on("right_z:move", function(pos) {
      console.log("Right Shoulder - Z:", pos);
    });
  }
});

Cylon.start();
```

**Comment by edgarsilva** [comment]
@acklenx also it seems you need to first pull the main cylon repo and merge the main master with your branch to be able to automaticaly merge.

**Comment by deadprogram** [comment]
I made merge and formatting fix corrections. @acklenx can you verify that the `master` on `cylon-joystick` still works for you? Thanks for the contributions!

**Pull request merged**
